/**
 * Download Baloo Bhaijaan 2 woff2 files from Google Fonts and emit a local
 * @font-face stylesheet. Self-hosting removes a third-party request on every
 * page load and keeps visitor IPs off Google's servers.
 *
 * Run once: node scripts/fetch-fonts.js
 */
import { writeFile } from 'node:fs/promises';
import { resolveInTheme } from './theme-paths.js';

const FAMILY = 'Baloo Bhaijaan 2';
const WEIGHTS = [400, 600, 700];
const SUBSETS_WANTED = ['latin', 'latin-ext', 'arabic'];

// A modern browser UA is required or Google serves legacy ttf instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const cssUrl =
  `https://fonts.googleapis.com/css2?family=${encodeURIComponent(FAMILY).replace(/%20/g, '+')}` +
  `:wght@${WEIGHTS.join(';')}&display=swap`;

/** Split the Google CSS into blocks, each preceded by its /* subset *\/ comment. */
function parseFaces(css) {
  const faces = [];
  const pattern = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  for (const match of css.matchAll(pattern)) {
    const [, subset, body] = match;
    const weight = /font-weight:\s*(\d+)/.exec(body)?.[1];
    const url = /url\((https:[^)]+\.woff2)\)/.exec(body)?.[1];
    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(body)?.[1]?.trim();
    if (subset && weight && url) faces.push({ subset, weight, url, unicodeRange });
  }
  return faces;
}

const css = await fetch(cssUrl, { headers: { 'User-Agent': UA } }).then((response) => {
  if (!response.ok) throw new Error(`Google Fonts returned ${response.status}`);
  return response.text();
});

const faces = parseFaces(css).filter((face) => SUBSETS_WANTED.includes(face.subset));
if (faces.length === 0) throw new Error('No matching @font-face blocks were parsed');

const blocks = [];
for (const face of faces) {
  const filename = `baloo-${face.subset}-${face.weight}.woff2`;
  const bytes = Buffer.from(
    await fetch(face.url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()),
  );
  if (bytes.subarray(0, 4).toString('latin1') !== 'wOF2') {
    throw new Error(`${filename} is not a woff2 file`);
  }
  await writeFile(resolveInTheme(`assets/${filename}`), bytes);
  console.log(`wrote assets/${filename} (${bytes.length} bytes)`);

  blocks.push(
    [
      '@font-face {',
      `  font-family: '${FAMILY}';`,
      '  font-style: normal;',
      `  font-weight: ${face.weight};`,
      '  font-display: swap;',
      `  src: url('${filename}') format('woff2');`,
      face.unicodeRange ? `  unicode-range: ${face.unicodeRange};` : null,
      '}',
    ]
      .filter(Boolean)
      .join('\n'),
  );
}

const header = `/* Baloo Bhaijaan 2 — SIL Open Font License 1.1. See OFL.txt.
   Generated by scripts/fetch-fonts.js. Do not edit by hand. */\n\n`;
await writeFile(resolveInTheme('assets/fonts.css'), header + blocks.join('\n\n') + '\n', 'utf8');
console.log(`wrote assets/fonts.css with ${blocks.length} faces`);
